version: '3.8'

services:
  # zkLove Frontend
  zklove-frontend:
    build: .
    container_name: zklove-app
    ports:
      - "80:80"
      - "443:443"  # For HTTPS (configure SSL certificates)
    environment:
      - NODE_ENV=production
    volumes:
      # Mount SSL certificates if using HTTPS
      - ./ssl:/etc/ssl/certs:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - zklove-network

  # Optional: Backend service (if you add one later)
  # zklove-backend:
  #   image: node:18-alpine
  #   container_name: zklove-backend
  #   working_dir: /app
  #   volumes:
  #     - ./backend:/app
  #   ports:
  #     - "3001:3001"
  #   environment:
  #     - NODE_ENV=production
  #   command: ["npm", "start"]
  #   networks:
  #     - zklove-network
  #   restart: unless-stopped

  # Optional: Database (if needed)
  # postgres:
  #   image: postgres:15-alpine
  #   container_name: zklove-db
  #   environment:
  #     POSTGRES_DB: zklove
  #     POSTGRES_USER: zklove
  #     POSTGRES_PASSWORD: your_secure_password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - zklove-network
  #   restart: unless-stopped

  # Optional: Redis for caching
  # redis:
  #   image: redis:7-alpine
  #   container_name: zklove-redis
  #   volumes:
  #     - redis_data:/data
  #   networks:
  #     - zklove-network
  #   restart: unless-stopped

networks:
  zklove-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
